### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by ca6samsuang** [fgrelard/OrthogonalPlaneBasedTools#1]
I have various problems in compiling this tool
All of them relate to DGtal
So please tell me the version numbers you used to compile this tool
especially boost，DGtal，cmake，eigen，ubuntu

Please give me a list like：
boost = 1.XX
DGtal = x.xx
````````

Thank you very much

**Comment by fgrelard** [comment]
Hi @ca6samsuang,

DGtal recently enforced stricter type conversion rules, see e.g. [PR #1345](https://github.com/DGtal-team/DGtal/pull/1345) which fixes PointVector implicit conversions. 
I fixed my code accordingly in commit [322f449](https://github.com/fgrelard/OrthogonalPlaneBasedTools/commit/322f4491a9465e60eab299667c9a86121c801d15). Please update your local repository, and let me know if compilation succeeds. If not, attach the errors which occur and the versions of your libraries.

For future reference, here are the versions of the libraries I am using on Ubuntu 18.04:
- DGtal =1.1
- boost = 1.65.1
- Eigen = 3.3.4-4
- QGLViewer =2.6.3 with Qt5
- ITK= 5.0 (Optional)

The following versions of these libraries should work on Ubuntu >= 14.04 (see [README.md](https://github.com/fgrelard/OrthogonalPlaneBasedTools/blob/master/README.md)):
- DGtal (>= 0.9)
- boost (>= 1.46)
- Eigen (>=3.2.0)
- QGLViewer (>=2.5.0) with Qt4 or Qt5
- ITK (>= 1.4)

**Comment by ca6samsuang** [comment]
This configuration works, thanks again.
The dependences I used have a little difference:
ubuntu=18.04, DGtal=1.0, boost=1.65, Eigen=3.3.4, QGLViewer =2.6.3 with Qt5
